### ISSUE TITLE
To do List - 8/23

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#114]
- Update firmware of QLXD1 on my desk. Might need to update the first receiver at Peppa as it was replaced unbeknownst to me with one from Lakehouse. (You might've updated that already, let's just double check). 

- Install / Wire ZEDi-10fx at VIM

- Continue with outstanding work at VIM (minus rigging).

**Comment by emerald-pham** [comment]
Created issue #115, #116. Relevant issues are #113 and #110. Will close this issue when those are done.

**Comment by emerald-pham** [comment]
Delaying ZEDfx

**Comment by emerald-pham** [comment]
QLXD receiver swapped out

**Comment by emerald-pham** [comment]
See #115 for updates

**Comment by emerald-pham** [comment]
Only outstanding issue remaining is #115. #110 (redline VIM) is not high on my list, but will likely get done tonight.

**Comment by emerald-pham** [comment]
Issue closed today, #115 resolved.
