### ISSUE TITLE
Try Locating an IEM Antenna Combiner

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#286]
I know that not too long ago we went over this, but before I have this quote submitted to finance for VMM RF equipment I want to be sure we don't have another RF Venue IEM combiner somewhere.. Can you check in lake-house and/or any other potential locations? The only one I'm aware of owning is the one at ski. Don't dwell on this too long, I don't want to waste too much time looking for something that doesn't exist.

**Comment by emerald-pham** [comment]
Acknowledged. In progress.

**Comment by emerald-pham** [comment]
Closed today, did not locate another active rack IEM combiner in the park.
