### ISSUE TITLE
Install Christmas Rehearsal Tracks onto iPads

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#330]
We have three rehearsal iPads inside of the production office. Each of them needs specific rehearsal tracks. In an email, you'll see each show and what iPad their rehearsal tracks need to be loaded on to. Note, we identify these iPads in colors. 

I'll forward you rehearsal tracks as they come in my inbox. This'll be something that takes a little bit of time.

**Comment by emerald-pham** [comment]
Closed by 612
