### ISSUE TITLE
Clean lake house

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#342]
Sweep, organize and throw out any unnecessary trash lying about. Michael has a small rolling case by the door that can stay put because it'll be used for Christmas.

**Comment by emerald-pham** [comment]
In progress. I would like to pull someone to assist next chance I get.

**Comment by emerald-pham** [comment]
Closed today. Cleared out most obvious stuff. Process ongoing in other issues.
