### ISSUE TITLE
Parkwide IEM Transmitter Receiver Inventory

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#355]
I might've had you do this before.. but can you make a spread sheet of what, where and how many IEM's we own. This includes the transmitter and receiver. 

Note, if it's deployed for BoT currently, include it in the spread sheet and just note where it currently is. I just need an overall understanding of how many units (Tx & Rx) we have.

**Comment by emerald-pham** [comment]
Lakehouse

1 P3RA J13
1 PSM300 P3T J13
1 PSM1000 G10

**Comment by emerald-pham** [comment]
P10r+ G10
P10r+ G10
P10r+ G10
P10r+ G10
PSM1000 G10

Ski

**Comment by emerald-pham** [comment]
Heartlake Hall receivers, Dots / DreamZZZ transmitters

**Comment by emerald-pham** [comment]
LCS, Kingdoms Stage

**Comment by emerald-pham** [comment]
Closed today.
