### ISSUE TITLE
Locate Suitable 10-8 TV Screen, 48~ Diagonal, or Inquire about New Sign from Sign Shop

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#356]
Refer to technical documentation on the G drive to see what TV was used (or Atleast how big.. and brand). Locate a viable TV and check it has HDMI inputs, also, find an appropriate wall mount bracket.

**Comment by emerald-pham** [comment]
Note to self - located @ G:\Park\Operations\Entertainment\10. Shows and Operations\4. Seasonal Entertainment\2022\8. Holidays\Shows

**Comment by emerald-pham** [comment]
No information about diagonal width of TV. Lightbar above TV appears to be 42", so estimating diagonal as 50", for now, with a 16:9 aspect ratio. Not going to use that number til' I check in with trout.

**Comment by emerald-pham** [comment]
He has that particular lightbar in his office.

**Comment by emerald-pham** [comment]
The lightbar in his office is 39", which indicates a diagonal of 45". However, I would like to get the correct dimensions from Zach B., so I'll briefly email him, although Amanda Jo mentions that Tony in the field may know the dimensions of the television.

**Comment by emerald-pham** [comment]
Wait, why don't I just ask scenic?

**Comment by emerald-pham** [comment]
Jody has offered to assist finding the outlined frame to find the dimensions. He has also offered Ricky's help in finding the border, as well, so we can measure the dimension, rather than estimating it.

**Comment by emerald-pham** [comment]
Zach B. reports there is a grey smaller skyview tv in lakehouse that was reserved for AAHC. I will need to find it by unwrapping the tvs on the bottom shelf, as none of the unwrapped tvs are the "grey" skyview tv noted here. In all likelihood I imagine it was taken for another purpose...

**Comment by emerald-pham** [comment]
Located grey TV near red tag area. Skyvue 74208. Diagonal measurement screen only of 41.5" approx. the screen appears to be 10-8 after plugging it in, I need to send it a test signal and then clean the vents.

**Comment by emerald-pham** [comment]
I need to inform Jody.

**Comment by emerald-pham** [comment]
Check ports, check model

**Comment by emerald-pham** [comment]
10-7 buttons, can't get to useful input.

**Comment by emerald-pham** [comment]
Located in our shop. Confirmed to be 48" diagonal. Will look for a correctly sized tv in lakehouse

**Comment by emerald-pham** [comment]
Closed
