### ISSUE TITLE
Prop mics for the carolers show

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#414]
Locate 3 broken handheld microphones for ENT to use for the roaming carolers show.

Note, they don't need to work. Pick some SM58 elements to go with them (make sure they don't look too bad.. and make sure they're not brand new either). 

Bring these to wardrobe for Stephanie so she can make decoration fittings for them.

**Comment by emerald-pham** [comment]
Closed today.
