### ISSUE TITLE
Brick-or-Treat Strike Details

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#478]
Here's an agenda for strike over the next week.

10/29
Zombie Cheer PA is coming down. Joe or I will strike the speakers and sub and have it transported to lake-house. 

10/30 
Caleb will strike all of the cables and antennas for Zombie Cheer.

10/31 
I'll need you to strike all of our rack equipment inside of Zombie Cheer (Dreamzzz IT rack). Refer to drawings for what is in there that needs to be removed so that you don't miss anything. 

I'll also need you to start striking Costume Parade. Start with the rack and work your way to the cables currently ran across the grass beds. The two speakers strapped to the pole are too high to unplug safely without a ladder and a spotter, so just wrap up the cable behind the pole. 

We need to find an answer for AHC's TV @LCS. Please continue to look for TV's that may be compatible, in the meantime I'll get answers on if there will be an overlay, if not, then we can get away with different sizes that aren't in the ballpark of 48". 

11/1
Costume Parade rack is struck. That rack is now built with NYE FW gear. 

I'll continue to update this issue with additional strike notes as they come. 

11/4 
Speakers and subwoofers were struck from fireworks area. 

11/5 
Please strike all power cables and XLR cables for the speakers at south stadium.

**Comment by emerald-pham** [comment]
Are you here today? By Joe, do you mean Jody G?

**Comment by emerald-pham** [comment]
I will try to strike fireworks today pending a golf cart, and ideally a hand cart

**Comment by emerald-pham** [comment]
@JoeDAlbano  Actually, you can see the overlay for AoHC in the shop - but yeah, a larger TV should work within an inch or two but will need to search harder. If I'm not misunderstanding you.

**Comment by emerald-pham** [comment]
Asked lighting for help striking amp to lakehouse. Need to strike 4 conductor, XLR, and power from North Stadium / subwoofer. Adding to EOD next time I'm at work.

**Comment by emerald-pham** [comment]
List of related issues

- [ ] #356
- [ ] #485
- [ ] #486
- [ ] #487

**Comment by emerald-pham** [comment]
Also added 

- [ ] #492 
- [ ] #491

**Comment by emerald-pham** [comment]
Issue closed.
