### ISSUE TITLE
Wire up subwoofer for Jingle Bricks

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#523]
Sub was dropped behind the hedge bush at market circle. Now that I'm remembering, the cable was speakon to speakon because we're going into the speakon patch of the outdoor rack box. So just hook up the sub again like it was for Halloween. (I believe we used speakon patch 2 or something..)

**Comment by emerald-pham** [comment]
Closed today. It was that patch, Lighting was nice enough to have labeled it. Reminds me to do similarly, and to go back and clean up that messy messy rack. It can be much nicer looking since there's not a lot going on there minus IT.
