### ISSUE TITLE
Mic check for Jingle Bricks 

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#524]
Do a full mic check at market circle after park close. Note, they're using headset mics, so get ULXD1's. (Btw, this is the carollers show. Jingle bricks is the actual name).

**Comment by emerald-pham** [comment]
Where did they want the charger - inside the rack?

**Comment by JoeDAlbano** [comment]
No, charger will probably be kept in 4D's green room but I'll confirm that later.

**Comment by emerald-pham** [comment]
What microphones did they want? I didn't spot any listed on the BoM unless I'm mistaken.

**Comment by JoeDAlbano** [comment]
Not sure about headsets yet. Itll probably be sm31FH's unless there's viable countrymen headsets for the sub-miniature approach.

**Comment by emerald-pham** [comment]
Didn't see a uci for market circle audio ala super cooper, so not testing that.

**Comment by emerald-pham** [comment]
Dipoles currently on case are both gband... swapping.

**Comment by emerald-pham** [comment]
Closed partially today.
