### ISSUE TITLE
Determine Fulcrum Acoustic CX8 coverage pattern by QSys schematic

### ISSUE THREAD

**Issue by emerald-pham** [emerald-pham/WorkRepo#562]

**Comment by JoeDAlbano** [comment]
The CX8's on top of fire rescue are 70 x 70 degree. The FH15's are 90 x 60 degree. 

An easy way to tell this is by looking on Qsys designs and looking at the name of the components, as most of the Fulcrums across the park have the exact model number on a schematic somewhere. For instance, the FH15's at LCS are FH1596, this means the 96 is the coverage pattern. Same goes for the CX8's, they're listed as CX877.

**Comment by emerald-pham** [comment]
Closed today. Thanks Joe.
