### ISSUE TITLE
Why does Sub218L show Speakon in product specs but phoenix irl and on spec sheet, unless we are mistaken? Is this what went at Grass Line?

### ISSUE THREAD

**Issue by emerald-pham** [emerald-pham/WorkRepo#563]
https://www.fulcrum-acoustic.com/wp-content/uploads/2019/09/Prod-Spec-Sub218L-v5.pdf

<img width="850" alt="image" src="https://github.com/emerald-pham/WorkRepo/assets/10377738/60ff9847-4253-47fc-b9ec-e69f84d26d40">

**Comment by emerald-pham** [comment]
<img width="228" alt="image" src="https://github.com/emerald-pham/WorkRepo/assets/10377738/9f6dd881-4008-404e-aca5-4bf0820ab24d">

**Comment by emerald-pham** [comment]
Also same problem with AD-S162T. 

Manual / spec sheets call for euroblock, whereas IRL seems to use screw terminal? Probably both inputs?

**Comment by emerald-pham** [comment]
No, wait, that QSC line array is euroblock.

**Comment by emerald-pham** [comment]
wait, lol. Screw terminal is another name for phoenix.

**Comment by JoeDAlbano** [comment]
Just seems like a mishap in their product specification. You can order this VLF-line subwoofer in install or touring options probably, so they just kept NL4 on there because who knows.

**Comment by emerald-pham** [comment]
Closed today. Thanks Joe.
