### ISSUE TITLE
To Do 11/30

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#566]
Here's a small list of things to look into this evening.

- Research cannon SFX for the non-pyro shows at BWSS. This was requested by the creative team so we're not offering a lackluster performance when pyro is down. This is more focused toward finding a sound for Calico's cannon signal that happens before V-Wake.
If/when you discover some decent options, put a copy of the current BWSS show on the macbook and throw those into the Qlab workspace so we can collectively listen to our options. Throw a couple in there if you find more than 1 decent SFX. 

- Begin cleaning the rack at ski, it needs it. Before we risk blowing up more amplifiers, it wouldn't hurt to grab some compressed air, rags and disinfectants to remove the surplus of dust and grime from that rack. When you're blowing out the vents/fans of different equipment, be mindful of not blowing out sensitive components and be sure not to blow the dust FURTHER into the units themself. While you're doing this, strike any unused equipment/cabling from the rack as well. Wear PPE..
        - General housekeeping of the booth would be appreciated if you have extra time tonight.

**Comment by emerald-pham** [comment]
Broken into subtasks.

- [ ] #567 
- [ ] #568

**Comment by emerald-pham** [comment]
- [ ] #571

**Comment by emerald-pham** [comment]
Closed today.
