### ISSUE TITLE
Find Ninjago Meet and Greet Music

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#613]
There's two M&G's during Ninjago Days. One at Bargain Shop and one at HeartLake Hall. Both of these require different meet and greet BGMs, so we need to locate the files. We can use Wu's music for HeartLake, but we still need the track for Bargain Shop. Can you look on Mia's core to see if the file exists there? If not, check the G drive and see if it lives on there anywhere.

**Comment by emerald-pham** [comment]
I located "Ninjago City BGM" on fun town factory core. Put onto my personal drive on your desk. Also in downloads folder, headend @JoeDAlbano

**Comment by emerald-pham** [comment]
Likely closed today. Comment if not closed.
