### ISSUE TITLE
KNYE Dance Party Install

### ISSUE THREAD

**Issue by JoeDAlbano** [emerald-pham/WorkRepo#626]
Its that time of year again.

During your opening shifts, please refer to the drawings on XTEN for a rack elevation and line schematic and begin working on whatever you can. I suggest putting together the rack firstly, but use the second Odyssee case, NOT the Viking case. I've made a patch panel (installed on the actual door) for said road case and it's in the shop next to my toolbox by the lockers. Once that's done, it wouldn't hurt to stage all of the necessary equipment including loudspeakers and cabling somewhere in lakehouse so I and a night crew can toss it into the space. 

Shoot me a text with any questions.

**Comment by emerald-pham** [comment]
Slightly tinned connectors on patch panel side. Largely occupied with calls today.

**Comment by emerald-pham** [comment]
Currently precariously low on patch length xlr. @JoeDAlbano your personal kit has a 1/8" to dual xlr, or was it just not striked properly?

**Comment by emerald-pham** [comment]
Closed on 12/24/2023
